In [1]:
import nltk

In [2]:
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.


True

In [3]:
from nltk.corpus import twitter_samples

In [4]:
positive_tweets=twitter_samples.strings('positive_tweets.json')
negative_tweets=twitter_samples.strings('negative_tweets.json')

In [5]:
positive_tweets[0]

'#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)'

In [6]:
import re

In [7]:
print(re.search("com","www.microsoft.com"))

<re.Match object; span=(14, 17), match='com'>


In [8]:
phone="1533-6678-87533  #this is mu number"

num=re.sub(r'#\w+',"",phone)
print(num)
num2=re.sub(r'\D+',"",phone)
print(num2)

1533-6678-87533   is mu number
1533667887533


In [9]:
text="tommorow is 2023/22/25 ,today is 2023/22/24"
num=re.findall(r'\d+',text)
print(num)

['2023', '22', '25', '2023', '22', '24']


In [10]:
print(re.findall(r'\d+/\d+/\d+',text))

['2023/22/25', '2023/22/24']


In [11]:
print(re.findall(r'[0-9]{1,2}',text))

['20', '23', '22', '25', '20', '23', '22', '24']


In [12]:
#[0-9] -->\d  
#\w -->[a-zA-Z0-9_]
text="tommorow is 2023/22/25 ,today_ is 2023/22/24"
num=re.findall(r'\w+',text)
print(num)

['tommorow', 'is', '2023', '22', '25', 'today_', 'is', '2023', '22', '24']


In [13]:
#[0-9] -->\d  
#\w -->[a-zA-Z0-9_]
text="tommorow is 2023/22/25 ,today_ is 2023/22/24"
num=re.findall(r'\S+',text)
print(num)

['tommorow', 'is', '2023/22/25', ',today_', 'is', '2023/22/24']


In [14]:
pos=positive_tweets[0]
pos

'#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)'

In [15]:
pos=re.sub(r"(#|@)\w+","",pos)
pos=re.sub(r'\d',"",pos)
pos=re.sub(r'(^\s+)',"",pos)
pos=re.sub(r'(\s+$)',"",pos)
pos

'for being top engaged members in my community this week :)'

In [16]:
from nltk.tokenize import TweetTokenizer
tokenizer=TweetTokenizer()
token=tokenizer.tokenize(pos)
print(token)

['for', 'being', 'top', 'engaged', 'members', 'in', 'my', 'community', 'this', 'week', ':)']


In [17]:
import nltk 
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
from nltk.corpus import stopwords
s_words=stopwords.words('english')
print(s_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [19]:
import string
punc=string.punctuation



In [20]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
tweet_clean=[]
for word in token:
    word=word.lower()
    if word not in s_words and  word not in punc:
        word=ps.stem(word)
        tweet_clean.append(word)

In [21]:
tweet_clean

['top', 'engag', 'member', 'commun', 'week', ':)']

In [22]:
def cleanText(text):
    text=re.sub(r'(#|@)[a-zA-Z0-9|_]+','',text) # remove hashtage ,@userName
    text=re.sub(r'RT[\s]+',' ',text) #removing retweets
    text=re.sub(r'https?:\/\/\S+',' ',text) #removing hyperlinks
    text=re.sub(r'\d',' ',text) #removing special characters
    text=re.sub(r'(^\s+)','',text)  # removing space in front text 
    text=re.sub(r'(\s+$)','',text) # removing space in tail text 
    return text



In [25]:
def process_sentance(sentances):
    result=[]
    #Stemming
    ps = PorterStemmer()
    for sentance in sentances:
        # Clean sentance
        sentance=cleanText(sentance)
        #tokenization
        sentance=sentance.split()
        #Remove Stopwords,speicial char
        sentance=[token for token in sentance if len(token) > 2  and token.lower() not in s_words and  token not in punc ]

        sentance=[ps.stem(word.lower()) for word in  sentance]
        result.append(sentance)
    return result

In [26]:
positive_tweets=process_sentance(positive_tweets)
negative_tweets=process_sentance(negative_tweets)

In [27]:
positive_tweets[0]

['top', 'engag', 'member', 'commun', 'week']

In [ ]:
[1,sum(pos)],sum(neg)]

In [ ]:
negative_tweets[0]

['hopeless', 'tmr']

In [28]:
for i in range(0,10):
    print(positive_tweets[i])

['top', 'engag', 'member', 'commun', 'week']
['hey', 'james!', 'odd', 'pleas', 'call', 'contact', 'centr', 'abl', 'assist', 'mani', 'thanks!']
['listen', 'last', 'night', 'bleed', 'amaz', 'track.', 'scotland?!']
['congrat']
['yeaaaah', 'yippppy!!!', 'accnt', 'verifi', 'rqst', 'succeed', 'got', 'blue', 'tick', 'mark', 'profil', 'day']
['one', 'irresist']
['like', 'keep', 'love', 'custom', 'wait', 'long!', 'hope', 'enjoy!', 'happi', 'friday!', 'lwwf']
['second', 'thought,', 'there’', 'enough', 'time', 'new', 'short', 'enter', 'system.', 'sheep', 'must', 'buying.']
['jgh', 'bayan', 'bye']
['act', 'mischievousness,', 'call', 'etl', 'layer', 'in-hous', 'wareh', 'app', 'katamari.', 'well…', 'name', 'impli', ':p.']


In [29]:
print("Positive length : ",len(positive_tweets))
print("Negative Length : ",len(negative_tweets))

Positive length :  5000
Negative Length :  5000


In [31]:
tweets=[]
labels=[]
for i in range(len(positive_tweets)):
    tweets.append(positive_tweets[i])
    tweets.append(negative_tweets[i])

    labels.append(1)
    labels.append(0)

print(len(tweets))
print(len(labels))

10000
10000


In [32]:
def build_freq(tweets,labels):
    freq={}
    for i in range(len(tweets)):

        for word in tweets[i]:
            
            if word not in  freq.keys():
                if labels[i]==1:
                    freq[word]=[1,0]#[pos,neg]
                else:
                    freq[word]=[0,1] #[pos,neg]
            else:
                if labels[i]==1:
                    freq[word][0]+=1
                else:
                    freq[word][1]+=1

    return freq

In [33]:
freq_dict=build_freq(tweets,labels)

In [34]:
freq_dict

{'top': [30, 6],
 'engag': [7, 0],
 'member': [15, 4],
 'commun': [31, 2],
 'week': [76, 49],
 'hopeless': [0, 2],
 'tmr': [1, 3],
 'hey': [61, 18],
 'james!': [3, 0],
 'odd': [2, 3],
 'pleas': [81, 257],
 'call': [36, 27],
 'contact': [7, 7],
 'centr': [2, 1],
 'abl': [8, 23],
 'assist': [1, 0],
 'mani': [29, 29],
 'thanks!': [19, 1],
 'everyth': [12, 13],
 'kid': [13, 13],
 'section': [3, 3],
 'ikea': [0, 1],
 'cute.': [1, 1],
 'shame': [1, 15],
 "i'm": [181, 339],
 'nearli': [3, 3],
 'month': [9, 17],
 'listen': [16, 18],
 'last': [46, 72],
 'night': [51, 40],
 'bleed': [2, 1],
 'amaz': [41, 11],
 'track.': [1, 0],
 'scotland?!': [1, 0],
 'heart': [10, 24],
 'slide': [0, 1],
 'wast': [2, 5],
 'basket.': [1, 1],
 'congrat': [19, 1],
 'hate': [13, 57],
 'japanes': [2, 3],
 '"bani"': [0, 2],
 ':(”': [0, 3],
 'yeaaaah': [1, 0],
 'yippppy!!!': [1, 0],
 'accnt': [1, 0],
 'verifi': [2, 0],
 'rqst': [1, 0],
 'succeed': [1, 0],
 'got': [67, 100],
 'blue': [9, 5],
 'tick': [1, 0],
 'mark': [1

In [35]:
import numpy as np
def build_vectors(tweets,freq_dict):

    vectors=[]
    for tweet in tweets:

        x=np.zeros(3)
        x[0]=1

        for word in tweet:
            x[1]+=freq_dict.get(word,0)[0]
            x[2]+=freq_dict.get(word,0)[1]

        vectors.append(x)

    return np.array(vectors)


In [36]:
X=build_vectors(tweets,freq_dict)

In [38]:
X.shape

(10000, 3)

In [37]:
X

array([[  1., 159.,  61.],
       [  1.,   1.,   5.],
       [  1., 249., 366.],
       ...,
       [  1.,   2.,   5.],
       [  1., 732., 149.],
       [  1., 105., 510.]])

In [40]:
y=np.array(labels)

In [41]:
X

array([[  1., 159.,  61.],
       [  1.,   1.,   5.],
       [  1., 249., 366.],
       ...,
       [  1.,   2.,   5.],
       [  1., 732., 149.],
       [  1., 105., 510.]])

In [42]:
y

array([1, 0, 1, ..., 0, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y=train_test_split(X,y,test_size=0.2,shuffle=True)  